language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hero0926/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hero0926/react-test npm test

after_success:
  - docker build -t hero0926/multi-client ./client
  - docker build -t hero0926/multi-nginx ./nginx
  - docker build -t hero0926/multi-server ./server
  - docker build -t hero0926/multi-worker ./worker

# log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push hero0926/multi-client
  - docker push hero0926/multi-nginx
  - docker push hero0926/multi-server
  - docker push hero0926/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-417600499985"
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    