language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hero/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hero/react-test npm test

after_success:
  - docker build -t hero/multi-client ./client
  - docker build -t hero/multi-nginx ./nginx
  - docker build -t hero/multi-server ./server
  - docker build -t hero/multi-worker ./worker

# log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push hero/multi-client
  - docker push hero/multi-nginx
  - docker push hero/multi-server
  - docker push hero/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-417600499985"
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
    